apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: poc
spec:
  serviceName: jenkins
  replicas: 2
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-claim
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts-jdk11
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jenkins-home
              mountPath: /var/jenkins_home